#!/usr/bin/env bash
# write a Bash script that will display information about the subdomains
DNSFunc() {
	DNS=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -n1 | tr "\t" " ")
	echo "$2 $DNS" | awk '{print "The subdomain " $1 " is a " $5 " record and points to " $6}'
}

if [ "$2" ]; then
	DNSFunc "$1" "$2"
else
	DNSFunc "$1" "www"
	DNSFunc "$1" "lb-01"
	DNSFunc "$1" "web-01"
	DNSFunc "$1" "web-02"
fi
