#!/usr/bin/env bash
#configures a new Ubuntu machine with Nginx web server
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start
