#!/usr/bin/env bash
#configures a new Ubuntu machine with Nginx web server
sudo apt -y install nginx
echo "<html><body><h1>Hello World!</h1></body></html>" > /var/www/html/index.html
echo "listen 80 default_server;" >> /etc/nginx/nginx.conf
sudo kill -s HUP $(cat /var/run/nginx.pid)
