#!/usr/bin/env bash
#configures a new Ubuntu machine with Nginx web server and redirect with 301
apt-get update
apt-get -y install nginx
sudo echo "Hello World!" > /var/www/html/index.html
sudo sed -i "location /redirect_me {\nreturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}\n" /etc/nginx/sites-available/default
sudo service nginx restart
