#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header
new_str="\t\tadd_header X-Served-By $hostname;\n\t\ttry_files $uri $uri/ =404;"
sudo sed -i "s/try_files $uri $uri\/ =404;/$new_str" /etc/nginx/sites-enabled/default
sudo service nginx restart
