#!/usr/bin/env bash
#configures a new Ubuntu machine to respect above requirements
sudo apt-get -y update
apt-get -y install haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "
frontend http
	bind *:80
	mode http
	default_backend web_server_backend

backend web_server_backend
	balance roundrobin
	server web_server_1 54.197.110.80:80 check
	server web_server_2 100.24.236.222:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
