#!/usr/bin/env bash
#configures a new Ubuntu machine to respect above requirements
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.9
sudo apt-get install haproxy=2.9.\*
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "
frontend http
	bind *:80
	mode http
	default_backend web_server_backend

backend web_server_backend
	balance roundrobin
	server web_server_1 54.197.110.80:80 check
	server web_server_2 100.24.236.222:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
